server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8584
          predicates:
            - Path=/patients/**

        - id: facture-service
          uri: http://localhost:8585
          predicates:
              - Path=/facture/factures/**